### ISSUE TITLE
UI: Style forms

### ISSUE THREAD

**Issue by gedankenstuecke** [OpenHumans/quantified-flu#20]
Currently our form fields are all pretty ugly and not styled at all. That's because the Django `modelForm` forms don't come with the proper markup that Bootstrap would expect.

An comparatively easy fix would be to add the standard bootstrap code to the forms.

**Comment by pythonmite** [comment]
Hello @gedankenstuecke I can help with this issue.

**Comment by gedankenstuecke** [comment]
Thanks, that would be awesome, @pythonmite!

**Comment by gedankenstuecke** [comment]
I think this is done too by now 👍
