### ISSUE TITLE
UI: Notes for retrospective events hidden

### ISSUE THREAD

**Issue by gedankenstuecke** [OpenHumans/quantified-flu#21]
Users can add notes to retrospective events, but this capability is rather hidden as it requires the following steps at this point: 1. create retrospective event 2. open event after creation 3. Click on "Edit event" on the event-page. 4. Write a note. 

Ideally the user should be able to write a note already during the creation of the event on the `/retrospective/add-event/`page.

**Comment by madprime** [comment]
I think "notes" are already exposed in the report form? This line added them, and (I just checked) the field is present in the (admittedly ugly :grimacing:) version on Heroku now.
https://github.com/OpenHumans/quantified-flu/blob/master/reports/forms.py#L22

**Comment by gedankenstuecke** [comment]
Aaaah, hadn't seen the update as I just looked after seeing the email. But maybe to make it clearer for potential contributors: 

![Screenshot 2020-03-31 at 18 28 01](https://user-images.githubusercontent.com/674899/78051102-7fc5d800-737d-11ea-954d-6771998296c9.png)

This is the form we're talking about, at `/retrospective/add-event/`. It should show the `notes` field to be filled right away if people choose to do so :)

**Comment by madprime** [comment]
Yeah, I can add this – I've got a fix for #22 too, and more stuff.

A lot of these UI things are really easy, but then I discover more issues in the process (and it seems pointless to be making issues here when I'm fixing things as I encounter them – apologies).
