### ISSUE TITLE
Additional physiological data sources/wearables? 

### ISSUE THREAD

**Issue by gedankenstuecke** [OpenHumans/quantified-flu#7]
Which additional data sources should we try to support? Supporting Apple Watches (see #6) seems like an easy one, but there's probably other widely used wearables that might be useful to support.

Which ones should we add to the list? Please leave a comment here with suggestions!

**Comment by michaelpuermayr** [comment]
Garmin has a wide range of wearables. Support for them would be very good!

**Comment by gedankenstuecke** [comment]
@michaelpuermayr Thanks for the suggestion! Do you have any Garmin wearable yourself?

**Comment by Akhil-Dhiman123** [comment]
I think smart patches can be considered good for wearable data collection.
Biobeat company has received CE mark approval for wristwatches and smart patches for measuring blood pressure, cardiac output ,stroke volume,heart rate and many other vital signals

**Comment by mishasaggi** [comment]
suggestion: oura ring. It's sleep tracking is detailed and they have a de API.
In their own app they have predictions based on HR, HRV, body temperature, breathing rate and user's activity.
Not the most popular wearable but very high quality data when compared with similar wearables.

**Comment by gedankenstuecke** [comment]
@mishasaggi Thanks, the Oura Ring is already supported and you can make plots of your nightly heart rates alongside the body temperature! :)

**Comment by gedankenstuecke** [comment]
Closing this as we have added support for all but Garmin (and that's in issue #27)
